#- name: "Setup Local Registry"
#  hosts: support
#  vars_files:
#    - ./roles/deploy_registry/vars/secrets.yml
#  become: True
#  become_method: sudo
#  become_user: root
#  roles:
#    - role: deploy_registry

#- name: "Mirror Openshift Install Images"
#  hosts: support
#  vars_files:
#    - ./roles/mirror_registry/vars/secrets.yml
#  roles:
#    - role: mirror_registry

#- name: "Create Support Server"
#  hosts: support
#  vars_files:
#    - ./roles/build_support_server/vars/secrets.yml
#  roles:
#    - role: build_support_server

- name: "Create DNS Records"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/create_dns_server/vars/main.yml
  roles:
    - role: create_dns_server

- name: "Create DHCP Server"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_dhcp_server
