- name: "Create Install Config"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_install_config
