---
# tasks file for pull_coreos_images

- name: Download Installer InitRamFS
  get_url:
    url: "{{ rhcos_mirror }}/{{ installer_initramfs_file }}"
    dest: "/var/lib/tftpboot/pxelinux/{{ installer_initramfs_file }}"

- name: Download Installer Kernel File
  get_url:
    url: "{{ rhcos_mirror }}/{{ installer_kernel_file }}"
    dest: "/var/lib/tftpboot/pxelinux/{{ installer_kernel_file }}"

- name: Download Metal BIOS Image
  get_url:
    url: "{{ rhcos_mirror }}/{{ installer_image_file }}"
    dest: "/var/www/html/{{ installer_image_file }}"

- name: Download OC Linux Client
  get_url:
    url: "{{ oc_files_url }}/{{ oc_client_url }}"
    dest: "{{ artifact_dir }}/{{ oc_client_url }}"

- name: Download OC Linux Installer
  get_url:
    url: "{{ oc_files_url }}/{{ oc_install_file }}"
    dest: "{{ artifact_dir }}/{{ oc_install_file }}"

- name: Copy oc client to path
  shell:
    cmd: tar -C /usr/local/bin -xvzpf "{{ artifact_dir }}/{{ oc_client_url }}" oc
